{{- if eq (include "eric-odp-ssh-broker.roleBinding" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "eric-odp-ssh-broker.name" . }}-psp-binding
  labels: {{- include "eric-odp-ssh-broker.labels" . | nindent 4 }}
  annotations: {{- include "eric-odp-ssh-broker.annotations" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: {{ include "eric-odp-ssh-broker.securityPolicyReference" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "eric-odp-ssh-broker.name" . }}-sa
{{- end -}}