apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-odp-ssh-broker.name" . }}
  labels:
    {{- include "eric-odp-ssh-broker.labels" . | indent 8 }}
  annotations:
    {{- include "eric-odp-ssh-broker.annotations" . | indent 4 }}
  namespace: {{ .Release.Namespace }}