
# As default registry path, the global registry path will be used.
#global:
#  timezone: UTC
#  registry:
#    url: armdocker.rnd.ericsson.se
#    imagePullPolicy: IfNotPresent
#  labels: { }
#  annotations: { }
#  log:
#    streamingMethod: "indirect" #Possible values are "indirect", "direct", "dual"


ldap:
  url:
  userDn:
  caSecret:

factory:
  url:
  certSecret:
  caSecret:

sso:
  url: https://sso/
  certSecret:
  caSecret:

ssh:
  hostKeySecret:
  tokenTypes:
  tokenDataField:
  applications:
   # Need to define at least one app
   # or the chart will fail to deploy
   - application: dummy
     port: 2200

replicaCount: 1

podDisruptionBudget:
  minAvailable : 50%

affinity:
  podAntiAffinity: "soft"
  topologyKey: "kubernetes.io/hostname"

annotations: { }

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imageCredentials:
  repoPath: # see default value in eric-product-info.yaml file
  pullSecret:

updateStrategy:
  # type can be OnDelete or RollingUpdate
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

service:
  type: ClusterIP
  ssh:
    port: 8001

container:
  ports:
    health: 8000
    metrics: 8001

resources:
  eric-odp-ssh-broker:
    limits:
      cpu: "100m"
      memory: "100Mi"
      ephemeral-storage: "128Mi"
    requests:
      cpu: "100m"
      memory: "100Mi"
      ephemeral-storage: "8Mi"
  logshipper:
    requests:
      memory: "50Mi"
      cpu: "50m"
    limits:
      memory: "100Mi"
      cpu: "100m"


# Custom labels
labels: { }

terminationGracePeriodSeconds: 30

tolerations: [ ]

probes:
  sshbroker:
    livenessProbe:
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 10
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 1
      periodSeconds: 10
      timeoutSeconds: 10
      successThreshold: 3
      failureThreshold: 3

podPriority:
  sshbroker:
    priorityClassName: ""

prometheus:
  scrape_role: pod
  scrape_interval: 1m

topologySpreadConstraints: [ ]

# DR D1123-127
appArmorProfile:
  # The setting applies to all container when the container name is omitted.
  # { choice='unconfined, runtime/default, localhost, "" ' } [ default="" ]
  type: ""

# DR D1123-128
seccompProfile:
  # The setting applies to all container when the container name is omitted.
  # { choice='unconfined, runtime/default, localhost, "" ' } [ default="" ]
  type: ""

extraInitContainers: []
extraInitContainersTemplate:
extraVolumes: []
extraVolumeMounts: []
extraEnv: []
