#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

modelVersion: 2.0

# converts vulnerability_report_2.0.md file to vulnerability_report_2.0.html
documents:
  - name: va-report
    files:
      - ../build/va-reports/vulnerability_report_2.0.md # path to vulnerability_report_2.0.md in the workspace